name: advent-of-code-2021
channels:
  - conda-forge
  - defaults
dependencies:
  - autoflake=1.4
  - black=21.10b0
  - flake8=3.9.2
  - isort=5.8.0
  - make=4.3
  - mypy=0.812
  - pip=21.2.4
  - pytest=6.2.4
  - python=3.9.5
